export const modules = {
    toolbar: [
      [{ header: [1, 2, 3, 4, 5, 6, false] }],
      ["bold", "italic", "underline"],
    //   ["bold", "italic", "underline", "strike"],
    //   ["link", "image", "video"],
    //   [{ list: "ordered" }, { list: "bullet" }],
    //   ["blockquote", "code-block"],
    //   [{ color: [] }, { background: [] }],
    //   ["clean"],
    //   ["paragraph"],
    //   [{ align: [] }],
    //   [{ font: [] }],
    //   [{ script: "sub" }, { script: "super" }],
    //   [{ indent: "-1" }, { indent: "+1" }],
    //   [{ direction: "rtl" }],
    ],
  };
  
  export const formats = [
    "bold",
    "italic",
    "underline",
    // "strike",
    // "blockquote",
    // "code-block",
    // "list",
    // "bullet",
    // "link",
    // "image",
    // "video",
    // "font",
    // "align",
    // "color",
    // "background",
    // "header",
    // "indent",
    // "size",
    // "script",
    // "clean",
    // "code",
    // "direction",
  ];